### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RocksteadyTC** [karai-project/base-client#1]
**ZedWallet fixes**

- [ ] Change currency unit suffix
- [ ] Change prompt's currency unit
- [ ] Add TX_EXTRA interactions (encode/decode)

**Daemon fixes**

- [ ] Seed nodes
- [ ] name for binary `karai-base-client`
- [ ] investigate CRYPTONOTE_MAX_BLOCK_BLOB_SIZE 
- [ ] investigate CRYPTONOTE_MAX_TX_SIZE
- [ ] Move TX_EXTRA params to src/CryptoNoteConfig.h
- [ ] Investigate p2p connection count
- [ ] Investigate fee address
- [ ] Investigate fee amount
- [ ] Optimize mixins, bootstrap change making. 
- [ ] Change network ID
- [ ] Change ports to fall outside common use range -> 10,001, 10,002

**General**

- [ ] Deploy Jerme's block size monitor
- [ ] Deploy turtlecoind-ha on karai seeds
